// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(Clothes2UDbContext))]
    partial class Clothes2UDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sae_clothes2u")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Models.EntityFramework.Abonnement", b =>
                {
                    b.Property<int>("AbonnementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("abo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AbonnementId"));

                    b.Property<int>("UtilisateurSuiveurId")
                        .HasColumnType("integer")
                        .HasColumnName("abo_utilisateur_suiveur");

                    b.Property<int>("UtilisateurSuivisId")
                        .HasColumnType("integer")
                        .HasColumnName("abo_utilisateur_suivis");

                    b.HasKey("AbonnementId");

                    b.HasIndex("UtilisateurSuiveurId");

                    b.HasIndex("UtilisateurSuivisId");

                    b.HasIndex("UtilisateurSuiveurId", "UtilisateurSuivisId")
                        .IsUnique();

                    b.ToTable("t_j_abonnement_abo", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Achete", b =>
                {
                    b.Property<int>("AcheteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ach_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AcheteId"));

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer")
                        .HasColumnName("ach_conversation_id");

                    b.Property<int>("UtilisateurAcheteurId")
                        .HasColumnType("integer")
                        .HasColumnName("ach_utilisateur_acheteur_id");

                    b.HasKey("AcheteId");

                    b.HasIndex("ConversationId")
                        .IsUnique()
                        .HasDatabaseName("idx_achete_conversation_unique");

                    b.HasIndex("UtilisateurAcheteurId")
                        .HasDatabaseName("idx_achete_utilisateur");

                    b.ToTable("t_j_achete_ach", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Adresse", b =>
                {
                    b.Property<int>("AdresseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("adr_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdresseId"));

                    b.Property<string>("AdrCodePostal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adr_code_postal");

                    b.Property<string>("AdresseRue")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("adr_rue");

                    b.Property<string>("AdresseVille")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("adr_ville");

                    b.HasKey("AdresseId");

                    b.ToTable("t_e_adresse_adr", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Annonce", b =>
                {
                    b.Property<int>("AnnonceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ann_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnnonceId"));

                    b.Property<int>("CategorieId")
                        .HasColumnType("integer")
                        .HasColumnName("ann_categorie_id");

                    b.Property<DateTime>("DateAnnonce")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ann_dateannonce");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ann_description");

                    b.Property<int>("EtatId")
                        .HasColumnType("integer")
                        .HasColumnName("ann_etat_id");

                    b.Property<int>("MarqueId")
                        .HasColumnType("integer")
                        .HasColumnName("ann_marque_id");

                    b.Property<bool>("Negociable")
                        .HasColumnType("boolean")
                        .HasColumnName("ann_negociable");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ann_prix");

                    b.Property<int>("SousCategorieId")
                        .HasColumnType("integer")
                        .HasColumnName("ann_sous_categorie_id");

                    b.Property<int>("StatutAnnonceId")
                        .HasColumnType("integer")
                        .HasColumnName("ann_statut_annonce_id");

                    b.Property<int>("TailleId")
                        .HasColumnType("integer")
                        .HasColumnName("ann_taille_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ann_titre");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer")
                        .HasColumnName("ann_utilisateur_id");

                    b.HasKey("AnnonceId");

                    b.HasIndex("CategorieId");

                    b.HasIndex("DateAnnonce");

                    b.HasIndex("EtatId");

                    b.HasIndex("MarqueId");

                    b.HasIndex("SousCategorieId");

                    b.HasIndex("StatutAnnonceId");

                    b.HasIndex("TailleId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("t_e_annonce_ann", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Bloque", b =>
                {
                    b.Property<int>("BloqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("blo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BloqueId"));

                    b.Property<int>("UtilisateurBloqueId")
                        .HasColumnType("integer")
                        .HasColumnName("blo_utilisateur_bloque_id");

                    b.Property<int>("UtilisateurBloqueurId")
                        .HasColumnType("integer")
                        .HasColumnName("blo_utilisateur_bloqueur_id");

                    b.HasKey("BloqueId");

                    b.HasIndex("UtilisateurBloqueId");

                    b.HasIndex("UtilisateurBloqueurId");

                    b.ToTable("t_e_bloque_blo", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Categorie", b =>
                {
                    b.Property<int>("CategorieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cat_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategorieId"));

                    b.Property<string>("LibelleCategorie")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cat_libelle_categorie");

                    b.HasKey("CategorieId");

                    b.ToTable("t_e_categorie_cat", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Conversation", b =>
                {
                    b.Property<int>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("con_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConversationId"));

                    b.Property<int>("AnnonceId")
                        .HasColumnType("integer")
                        .HasColumnName("con_annonce_id");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("con_datecreation");

                    b.Property<int>("StatutConversationId")
                        .HasColumnType("integer")
                        .HasColumnName("con_statut_conversation_id");

                    b.HasKey("ConversationId");

                    b.HasIndex("AnnonceId");

                    b.HasIndex("StatutConversationId");

                    b.ToTable("t_e_conversation_con", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Couleur", b =>
                {
                    b.Property<int>("CouleurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cou_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CouleurId"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cou_nom");

                    b.HasKey("CouleurId");

                    b.ToTable("t_e_couleur_cou", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Decision_suspension", b =>
                {
                    b.Property<int>("Decision_suspensionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sus_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Decision_suspensionId"));

                    b.Property<int?>("AnnonceId")
                        .HasColumnType("integer")
                        .HasColumnName("sus_annonce_id");

                    b.Property<DateTime>("DateDebutSuspension")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sus_date_debut_suspension");

                    b.Property<DateTime>("DateFinSuspension")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sus_date_fin_suspension");

                    b.Property<bool>("EstTraitee")
                        .HasColumnType("boolean")
                        .HasColumnName("sus_traitee");

                    b.Property<string>("MotifSuspension")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sus_motif_suspension");

                    b.Property<int>("TypeSuspensionId")
                        .HasColumnType("integer")
                        .HasColumnName("sus_type_id");

                    b.Property<int?>("UtilisateurAdminId")
                        .HasColumnType("integer")
                        .HasColumnName("sus_utilisateur_admin_id");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("integer")
                        .HasColumnName("sus_utilisateur_id");

                    b.HasKey("Decision_suspensionId");

                    b.HasIndex("AnnonceId")
                        .HasDatabaseName("idx_decision_suspension_annonce");

                    b.HasIndex("TypeSuspensionId")
                        .HasDatabaseName("idx_decision_suspension_type");

                    b.HasIndex("UtilisateurAdminId");

                    b.HasIndex("UtilisateurId")
                        .HasDatabaseName("idx_decision_suspension_utilisateur");

                    b.HasIndex("DateDebutSuspension", "DateFinSuspension")
                        .HasDatabaseName("idx_decision_suspension_dates");

                    b.ToTable("t_e_decision_suspension_sus", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.DemandeRestauration", b =>
                {
                    b.Property<int>("DemandeRestaurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("demres_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DemandeRestaurationId"));

                    b.Property<string>("DemandeRestaurationText")
                        .HasColumnType("text")
                        .HasColumnName("demres_demande_restauration");

                    b.Property<int>("SuspensionId")
                        .HasColumnType("integer")
                        .HasColumnName("demres_suspension_id");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer")
                        .HasColumnName("demres_utilisateur_id");

                    b.HasKey("DemandeRestaurationId");

                    b.HasIndex("SuspensionId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("t_e_demande_restauration_demres", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Est_De_Couleur", b =>
                {
                    b.Property<int>("EstDeCouleurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("edc_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EstDeCouleurId"));

                    b.Property<int>("AnnonceId")
                        .HasColumnType("integer")
                        .HasColumnName("edc_annonce_id");

                    b.Property<int>("CouleurId")
                        .HasColumnType("integer")
                        .HasColumnName("edc_couleur_id");

                    b.HasKey("EstDeCouleurId");

                    b.HasIndex("AnnonceId");

                    b.HasIndex("CouleurId");

                    b.ToTable("t_j_est_de_couleur_edc", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.EtatArticle", b =>
                {
                    b.Property<int>("EtatArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("etaart_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EtatArticleId"));

                    b.Property<string>("NomEtat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("etaart_nometat");

                    b.HasKey("EtatArticleId");

                    b.ToTable("t_e_etatarticle_etaart", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Favoris", b =>
                {
                    b.Property<int>("FavorisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("fav_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FavorisId"));

                    b.Property<int>("AnnonceId")
                        .HasColumnType("integer")
                        .HasColumnName("fav_annonce_id");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer")
                        .HasColumnName("fav_utilisateur_id");

                    b.HasKey("FavorisId");

                    b.HasIndex("AnnonceId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("t_j_favoris_fav", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Illustre_Annonce", b =>
                {
                    b.Property<int>("IllustId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("illann_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IllustId"));

                    b.Property<int>("AnnonceId")
                        .HasColumnType("integer")
                        .HasColumnName("illann_annonce_id");

                    b.Property<int>("PhotoId")
                        .HasColumnType("integer")
                        .HasColumnName("illann_photo_id");

                    b.HasKey("IllustId");

                    b.HasIndex("PhotoId");

                    b.HasIndex("AnnonceId", "PhotoId")
                        .IsUnique();

                    b.ToTable("t_j_illustre_annonce_illann", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Marque", b =>
                {
                    b.Property<int>("MarqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mar_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MarqueId"));

                    b.Property<string>("NomMarque")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mar_nommarque");

                    b.HasKey("MarqueId");

                    b.ToTable("t_e_marque_mar", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mes_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageId"));

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer")
                        .HasColumnName("mes_conversation_id");

                    b.Property<DateTime>("MessageDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mes_date_envoie");

                    b.Property<bool>("MessageLu")
                        .HasColumnType("boolean")
                        .HasColumnName("mes_lu");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer")
                        .HasColumnName("mes_utilisateur_id");

                    b.HasKey("MessageId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("t_e_message_mes", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.MessageContientImage", b =>
                {
                    b.Property<int>("MessageContientImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("messconima_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageContientImageId"));

                    b.Property<int>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("messconima_message_id");

                    b.Property<int>("PhotoId")
                        .HasColumnType("integer")
                        .HasColumnName("messconima_image_id");

                    b.HasKey("MessageContientImageId");

                    b.HasIndex("PhotoId");

                    b.HasIndex("MessageId", "PhotoId")
                        .IsUnique();

                    b.ToTable("t_j_message_contient_image_messconima", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.MessageDemande", b =>
                {
                    b.Property<int>("MessageDemandeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mesdem_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageDemandeId"));

                    b.Property<int?>("DemandeId")
                        .HasColumnType("integer")
                        .HasColumnName("mesdem_demande_id");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("mesdem_message_id");

                    b.HasKey("MessageDemandeId");

                    b.HasIndex("DemandeId");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("t_e_message_demande_mesdem", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.MessageTexte", b =>
                {
                    b.Property<int>("MessageTexteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mestex_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageTexteId"));

                    b.Property<string>("ContenuMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mestex_contenu_message");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("mestex_message_id");

                    b.HasKey("MessageTexteId");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("t_e_message_texte_mestex", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.MessageValidation", b =>
                {
                    b.Property<int>("MessageValidationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mesval_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageValidationId"));

                    b.Property<int>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("mesval_message_id");

                    b.HasKey("MessageValidationId");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("t_e_message_validation_mesval", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.NoteUtilisateur", b =>
                {
                    b.Property<int>("NoteUtilisateurId")
                        .HasColumnType("integer")
                        .HasColumnName("notuti_id");

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("notuti_commentaire");

                    b.Property<DateTime>("DatePublication")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("notuti_date");

                    b.Property<int>("Note")
                        .HasColumnType("integer")
                        .HasColumnName("notuti_note");

                    b.Property<int>("NoteId")
                        .HasColumnType("integer")
                        .HasColumnName("notuti_note_id");

                    b.Property<int>("NoteurId")
                        .HasColumnType("integer")
                        .HasColumnName("notuti_noteur_id");

                    b.HasKey("NoteUtilisateurId");

                    b.HasIndex("NoteId");

                    b.ToTable("t_e_note_utilisateur_notuti", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("not_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("not_type_id");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer")
                        .HasColumnName("not_utilisateur_id");

                    b.HasKey("NotificationId");

                    b.HasIndex("NotificationTypeId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("t_e_notification_not", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.NotificationAdmin", b =>
                {
                    b.Property<int>("NotificationAdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("notadm_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationAdminId"));

                    b.Property<string>("AdminText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notadm_admin_text");

                    b.Property<int>("NotificationId")
                        .HasColumnType("integer")
                        .HasColumnName("notadm_notification_id");

                    b.HasKey("NotificationAdminId");

                    b.HasIndex("NotificationId")
                        .IsUnique();

                    b.ToTable("t_e_notification_admin_notadm", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.NotificationAvertissement", b =>
                {
                    b.Property<int>("NotificationAvertissementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("notave_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationAvertissementId"));

                    b.Property<string>("MessageAvertissement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notave_avertissement_message");

                    b.Property<int>("NotificationId")
                        .HasColumnType("integer")
                        .HasColumnName("notave_notification_id");

                    b.HasKey("NotificationAvertissementId");

                    b.HasIndex("NotificationId")
                        .IsUnique();

                    b.ToTable("t_e_notification_avertissement_notave", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.NotificationMessage", b =>
                {
                    b.Property<int>("NotificationMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("notmes_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationMessageId"));

                    b.Property<int>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("notmes_message_id");

                    b.Property<int>("NotificationId")
                        .HasColumnType("integer")
                        .HasColumnName("notmes_notification_id");

                    b.HasKey("NotificationMessageId");

                    b.HasIndex("MessageId");

                    b.HasIndex("NotificationId")
                        .IsUnique();

                    b.ToTable("t_e_notification_message_notmes", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.NotificationModificationAnnonce", b =>
                {
                    b.Property<int>("NotificationModificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("notmod_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationModificationId"));

                    b.Property<int>("AnnonceId")
                        .HasColumnType("integer")
                        .HasColumnName("notmod_annonce_id");

                    b.Property<int>("NotificationId")
                        .HasColumnType("integer")
                        .HasColumnName("notmod_notification_id");

                    b.HasKey("NotificationModificationId");

                    b.HasIndex("AnnonceId");

                    b.HasIndex("NotificationId")
                        .IsUnique();

                    b.ToTable("t_e_notification_modifiaction_notmod", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.NotificationNouvelleAnnonce", b =>
                {
                    b.Property<int>("NotificationNouvelleAnnonceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("notnou_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationNouvelleAnnonceId"));

                    b.Property<int>("AnnonceId")
                        .HasColumnType("integer")
                        .HasColumnName("notnou_annonce_id");

                    b.Property<int>("NotificationId")
                        .HasColumnType("integer")
                        .HasColumnName("notnou_notification_id");

                    b.HasKey("NotificationNouvelleAnnonceId");

                    b.HasIndex("AnnonceId");

                    b.HasIndex("NotificationId")
                        .IsUnique();

                    b.ToTable("t_e_notification_nouvelle_annonce_notnou", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.NotificationType", b =>
                {
                    b.Property<int>("NotificationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("nottyp_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationTypeId"));

                    b.Property<string>("LibelleType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nottyp_libelle_type");

                    b.HasKey("NotificationTypeId");

                    b.ToTable("t_e_notification_type_nottyp", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Photo", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pho_photo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PhotoId"));

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("pho_image");

                    b.HasKey("PhotoId");

                    b.ToTable("t_e_photo_pho", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Recense", b =>
                {
                    b.Property<int>("RecenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rec_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecenseId"));

                    b.Property<int>("AnnonceId")
                        .HasColumnType("integer")
                        .HasColumnName("rec_annonce_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("rec_tag_id");

                    b.HasKey("RecenseId");

                    b.HasIndex("AnnonceId");

                    b.HasIndex("TagId");

                    b.ToTable("t_j_recense_rec", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.RoleUtilisateur", b =>
                {
                    b.Property<int>("RoleUtilisateurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("roluti_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleUtilisateurId"));

                    b.Property<string>("RoleUtilisateurLibelle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("roluti_libelle");

                    b.HasKey("RoleUtilisateurId");

                    b.ToTable("t_e_role_utilisateur_roluti", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Signalement", b =>
                {
                    b.Property<int>("SignalementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sig_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SignalementId"));

                    b.Property<DateTime>("SignalementDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sig_date");

                    b.Property<string>("SignalementMotif")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sig_motif");

                    b.Property<int>("SignalementTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("sig_type_id");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer")
                        .HasColumnName("sig_utilisateur_id");

                    b.HasKey("SignalementId");

                    b.HasIndex("SignalementDate")
                        .HasDatabaseName("idx_signalement_date");

                    b.HasIndex("SignalementTypeId")
                        .HasDatabaseName("idx_signalement_type");

                    b.HasIndex("UtilisateurId")
                        .HasDatabaseName("idx_signalement_utilisateur");

                    b.ToTable("t_e_signalement_sig", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.SignalementAnnonce", b =>
                {
                    b.Property<int>("SignalementAnnonceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sigan_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SignalementAnnonceId"));

                    b.Property<int>("AnnonceSignaleeId")
                        .HasColumnType("integer")
                        .HasColumnName("sigan_annonce_signalee_id");

                    b.Property<int>("SignalementId")
                        .HasColumnType("integer")
                        .HasColumnName("sigan_signalement_id");

                    b.HasKey("SignalementAnnonceId");

                    b.HasIndex("AnnonceSignaleeId")
                        .HasDatabaseName("idx_signalement_annonce_annonce");

                    b.HasIndex("SignalementId")
                        .IsUnique()
                        .HasDatabaseName("idx_signalement_annonce_signalement_unique");

                    b.ToTable("t_e_signalement_annonce_sigan", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.SignalementAvis", b =>
                {
                    b.Property<int>("SignalementAvisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sigavs_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SignalementAvisId"));

                    b.Property<int>("AvisId")
                        .HasColumnType("integer")
                        .HasColumnName("sigavs_avis_id");

                    b.Property<int>("SignalementId")
                        .HasColumnType("integer")
                        .HasColumnName("sigavs_signalement_id");

                    b.HasKey("SignalementAvisId");

                    b.HasIndex("AvisId")
                        .HasDatabaseName("idx_signalement_avis_avis");

                    b.HasIndex("SignalementId")
                        .IsUnique()
                        .HasDatabaseName("idx_signalement_avis_signalement_unique");

                    b.ToTable("t_e_signalement_avis_sigavs", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.SignalementUtilisateur", b =>
                {
                    b.Property<int>("SignalementUtilisateurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("siguti_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SignalementUtilisateurId"));

                    b.Property<int>("SignalementId")
                        .HasColumnType("integer")
                        .HasColumnName("siguti_signalement_id");

                    b.Property<int>("UtilisateurSignaleId")
                        .HasColumnType("integer")
                        .HasColumnName("siguti_utilisateur_signale_id");

                    b.HasKey("SignalementUtilisateurId");

                    b.HasIndex("SignalementId")
                        .IsUnique()
                        .HasDatabaseName("idx_signalement_utilisateur_signalement_unique");

                    b.HasIndex("UtilisateurSignaleId")
                        .HasDatabaseName("idx_signalement_utilisateur_utilisateur");

                    b.ToTable("t_e_signalement_utilisateur_siguti", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.SousCategorie", b =>
                {
                    b.Property<int>("SousCategorieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sscat_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SousCategorieId"));

                    b.Property<int>("CategorieId")
                        .HasColumnType("integer")
                        .HasColumnName("sscat_categorie_id");

                    b.Property<string>("LibelleSousCategorie")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sscat_libelle_sous_categorie");

                    b.HasKey("SousCategorieId");

                    b.HasIndex("CategorieId");

                    b.ToTable("t_e_souscategorie_sscat", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.StatutAnnonce", b =>
                {
                    b.Property<int>("StatutAnnonceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("staann_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatutAnnonceId"));

                    b.Property<string>("StatutLibelle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("staan_libelle_statut");

                    b.HasKey("StatutAnnonceId");

                    b.ToTable("t_e_statut_annonce_staann", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.StatutConversation", b =>
                {
                    b.Property<int>("StatutConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sta_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatutConversationId"));

                    b.Property<string>("StatutConversationLibelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sta_libelle");

                    b.HasKey("StatutConversationId");

                    b.HasIndex("StatutConversationLibelle")
                        .IsUnique()
                        .HasDatabaseName("idx_statut_conversation_libelle_unique");

                    b.ToTable("t_e_statut_conversation_sta", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.StatutUtilisateur", b =>
                {
                    b.Property<int>("StatutUtilisateurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("stauti_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatutUtilisateurId"));

                    b.Property<string>("StatutLibelle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stauti_libelle_statut");

                    b.HasKey("StatutUtilisateurId");

                    b.ToTable("t_e_statut_stauti", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<string>("LibelleTag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag_libelle");

                    b.HasKey("TagId");

                    b.ToTable("t_e_tag_tag", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Taille", b =>
                {
                    b.Property<int>("TailleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tai_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TailleId"));

                    b.Property<int>("CategorieTailleId")
                        .HasColumnType("integer")
                        .HasColumnName("tai_categorie_taille_id");

                    b.Property<string>("Libelletaille")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tai_libelletaille");

                    b.HasKey("TailleId");

                    b.HasIndex("CategorieTailleId");

                    b.ToTable("t_e_taille_tai", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tra_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer")
                        .HasColumnName("tra_conversation_id");

                    b.Property<int>("TransactionEtat")
                        .HasColumnType("integer")
                        .HasColumnName("tra_transaction_etat");

                    b.Property<int>("TransactionMontant")
                        .HasColumnType("integer")
                        .HasColumnName("tra_montant");

                    b.HasKey("TransactionId");

                    b.HasIndex("ConversationId")
                        .IsUnique()
                        .HasDatabaseName("idx_transaction_conversation_unique");

                    b.HasIndex("TransactionEtat")
                        .HasDatabaseName("idx_transaction_etat");

                    b.ToTable("t_e_transaction_tra", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.TypeSignalement", b =>
                {
                    b.Property<int>("SignalementTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sigtype_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SignalementTypeId"));

                    b.Property<string>("SignalementTypeLibelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sigtyp_libelle_type");

                    b.HasKey("SignalementTypeId");

                    b.HasIndex("SignalementTypeLibelle")
                        .IsUnique()
                        .HasDatabaseName("idx_type_signalement_libelle_unique");

                    b.ToTable("t_e_signalement_type_sigtyp", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.TypeSuspension", b =>
                {
                    b.Property<int>("TypeSuspensionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tsu_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeSuspensionId"));

                    b.Property<string>("NomTypeSuspension")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tsu_nomtypesuspension");

                    b.HasKey("TypeSuspensionId");

                    b.HasIndex("NomTypeSuspension")
                        .IsUnique()
                        .HasDatabaseName("idx_type_suspension_nom_unique");

                    b.ToTable("t_e_type_suspension_tsu", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Utilisateur", b =>
                {
                    b.Property<int>("UtilisateurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("uti_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UtilisateurId"));

                    b.Property<int?>("AdresseId")
                        .HasColumnType("integer")
                        .HasColumnName("uti_adresse_id");

                    b.Property<DateTime>("Dateinscription")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uti_dateinscription");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("uti_description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("uti_email");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("uti_login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("uti_password");

                    b.Property<int?>("PhotoId")
                        .HasColumnType("integer")
                        .HasColumnName("uti_id_photo");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("uti_role_id");

                    b.Property<int>("StatutId")
                        .HasColumnType("integer")
                        .HasColumnName("uti_statut_id");

                    b.HasKey("UtilisateurId");

                    b.HasIndex("AdresseId");

                    b.HasIndex("Dateinscription");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("PhotoId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("StatutId");

                    b.ToTable("t_e_utilisateur_uti", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Vend", b =>
                {
                    b.Property<int>("VendId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ven_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VendId"));

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer")
                        .HasColumnName("ven_conversation_id");

                    b.Property<int>("UtilisateurVendeurId")
                        .HasColumnType("integer")
                        .HasColumnName("ven_utilisateur_vendeur_id");

                    b.HasKey("VendId");

                    b.HasIndex("ConversationId")
                        .IsUnique()
                        .HasDatabaseName("idx_vend_conversation_unique");

                    b.HasIndex("UtilisateurVendeurId")
                        .HasDatabaseName("idx_vend_utilisateur");

                    b.ToTable("t_j_vend_ven", "sae_clothes2u");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Abonnement", b =>
                {
                    b.HasOne("API.Models.EntityFramework.Utilisateur", "UtilisateurSuiveur")
                        .WithMany("Abonnements")
                        .HasForeignKey("UtilisateurSuiveurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.Utilisateur", "UtilisateurSuivis")
                        .WithMany("Abonnes")
                        .HasForeignKey("UtilisateurSuivisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_t_j_abonnement_abo_t_e_utilisateur_uti_abo_utilisateur_sui~1");

                    b.Navigation("UtilisateurSuiveur");

                    b.Navigation("UtilisateurSuivis");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Achete", b =>
                {
                    b.HasOne("API.Models.EntityFramework.Conversation", "Conversation")
                        .WithOne("Acheteur")
                        .HasForeignKey("API.Models.EntityFramework.Achete", "ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.Utilisateur", "UtilisateurAcheteur")
                        .WithMany("Achats")
                        .HasForeignKey("UtilisateurAcheteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("UtilisateurAcheteur");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Annonce", b =>
                {
                    b.HasOne("API.Models.EntityFramework.Categorie", "Categorie")
                        .WithMany("Annonces")
                        .HasForeignKey("CategorieId")
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.EtatArticle", "Etat")
                        .WithMany("Annonces")
                        .HasForeignKey("EtatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.Marque", "Marque")
                        .WithMany("Annonces")
                        .HasForeignKey("MarqueId")
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.SousCategorie", "SousCategorie")
                        .WithMany("Annonces")
                        .HasForeignKey("SousCategorieId")
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.StatutAnnonce", "Statut")
                        .WithMany("Annonces")
                        .HasForeignKey("StatutAnnonceId")
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.Taille", "Taille")
                        .WithMany("Annonces")
                        .HasForeignKey("TailleId")
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.Utilisateur", "Utilisateur")
                        .WithMany("Annonces")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("Etat");

                    b.Navigation("Marque");

                    b.Navigation("SousCategorie");

                    b.Navigation("Statut");

                    b.Navigation("Taille");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Bloque", b =>
                {
                    b.HasOne("API.Models.EntityFramework.Utilisateur", "UtilisateurBloque")
                        .WithMany("BloqueParUtilisateurs")
                        .HasForeignKey("UtilisateurBloqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.Utilisateur", "UtilisateurBloqueur")
                        .WithMany("UtilisateursBloques")
                        .HasForeignKey("UtilisateurBloqueurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UtilisateurBloque");

                    b.Navigation("UtilisateurBloqueur");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Conversation", b =>
                {
                    b.HasOne("API.Models.EntityFramework.Annonce", "LAnnonce")
                        .WithMany("LesConversations")
                        .HasForeignKey("AnnonceId")
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.StatutConversation", "StatutConversation")
                        .WithMany("Conversations")
                        .HasForeignKey("StatutConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LAnnonce");

                    b.Navigation("StatutConversation");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Decision_suspension", b =>
                {
                    b.HasOne("API.Models.EntityFramework.Annonce", "AnnonceSuspendu")
                        .WithMany("Decisions")
                        .HasForeignKey("AnnonceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.Models.EntityFramework.TypeSuspension", "TypeSuspension")
                        .WithMany("Decision_suspensions")
                        .HasForeignKey("TypeSuspensionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.Utilisateur", "Decisionnaire")
                        .WithMany("LesDecisions")
                        .HasForeignKey("UtilisateurAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.Models.EntityFramework.Utilisateur", "UtilisateurSuspendu")
                        .WithMany("LesSuspensions")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_t_e_decision_suspension_sus_t_e_utilisateur_uti_sus_utilis~1");

                    b.Navigation("AnnonceSuspendu");

                    b.Navigation("Decisionnaire");

                    b.Navigation("TypeSuspension");

                    b.Navigation("UtilisateurSuspendu");
                });

            modelBuilder.Entity("API.Models.EntityFramework.DemandeRestauration", b =>
                {
                    b.HasOne("API.Models.EntityFramework.Decision_suspension", "Suspension")
                        .WithMany("DemandesRes")
                        .HasForeignKey("SuspensionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.Utilisateur", "Plaignant")
                        .WithMany("DemandesRestauration")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plaignant");

                    b.Navigation("Suspension");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Est_De_Couleur", b =>
                {
                    b.HasOne("API.Models.EntityFramework.Annonce", "Annonce")
                        .WithMany("Couleurs")
                        .HasForeignKey("AnnonceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.Couleur", "Couleur")
                        .WithMany("Annonces")
                        .HasForeignKey("CouleurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Annonce");

                    b.Navigation("Couleur");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Favoris", b =>
                {
                    b.HasOne("API.Models.EntityFramework.Annonce", "Annonce")
                        .WithMany("UtilisateursFavoris")
                        .HasForeignKey("AnnonceId")
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.Utilisateur", "Utilisateur")
                        .WithMany("AnnoncesFavorites")
                        .HasForeignKey("UtilisateurId")
                        .IsRequired();

                    b.Navigation("Annonce");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Illustre_Annonce", b =>
                {
                    b.HasOne("API.Models.EntityFramework.Annonce", "Annonce")
                        .WithMany("Photos")
                        .HasForeignKey("AnnonceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.Photo", "Photo")
                        .WithMany("Annonces")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Annonce");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Message", b =>
                {
                    b.HasOne("API.Models.EntityFramework.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.Utilisateur", "Utilisateur")
                        .WithMany("Messages")
                        .HasForeignKey("UtilisateurId")
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("API.Models.EntityFramework.MessageContientImage", b =>
                {
                    b.HasOne("API.Models.EntityFramework.MessageTexte", "Message")
                        .WithMany("Photos")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.Photo", "Photo")
                        .WithMany("Messages")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("API.Models.EntityFramework.MessageDemande", b =>
                {
                    b.HasOne("API.Models.EntityFramework.MessageDemande", "Offre")
                        .WithMany("ContreOffres")
                        .HasForeignKey("DemandeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("API.Models.EntityFramework.Message", "Message")
                        .WithOne("MessageDemande")
                        .HasForeignKey("API.Models.EntityFramework.MessageDemande", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("Offre");
                });

            modelBuilder.Entity("API.Models.EntityFramework.MessageTexte", b =>
                {
                    b.HasOne("API.Models.EntityFramework.Message", "Message")
                        .WithOne("MessageTexte")
                        .HasForeignKey("API.Models.EntityFramework.MessageTexte", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("API.Models.EntityFramework.MessageValidation", b =>
                {
                    b.HasOne("API.Models.EntityFramework.Message", "Message")
                        .WithOne("MessageValidation")
                        .HasForeignKey("API.Models.EntityFramework.MessageValidation", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("API.Models.EntityFramework.NoteUtilisateur", b =>
                {
                    b.HasOne("API.Models.EntityFramework.Utilisateur", "Cible")
                        .WithMany("NotesCible")
                        .HasForeignKey("NoteId")
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.Utilisateur", "Auteur")
                        .WithMany("NotesAuteur")
                        .HasForeignKey("NoteUtilisateurId")
                        .IsRequired();

                    b.Navigation("Auteur");

                    b.Navigation("Cible");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Notification", b =>
                {
                    b.HasOne("API.Models.EntityFramework.NotificationType", "NotificationType")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.Utilisateur", "Utilisateur")
                        .WithMany("Notifications")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationType");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("API.Models.EntityFramework.NotificationAdmin", b =>
                {
                    b.HasOne("API.Models.EntityFramework.Notification", "LaNotification")
                        .WithOne("NotificationAdmins")
                        .HasForeignKey("API.Models.EntityFramework.NotificationAdmin", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LaNotification");
                });

            modelBuilder.Entity("API.Models.EntityFramework.NotificationAvertissement", b =>
                {
                    b.HasOne("API.Models.EntityFramework.Notification", "LaNotification")
                        .WithOne("NotificationAvertissements")
                        .HasForeignKey("API.Models.EntityFramework.NotificationAvertissement", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LaNotification");
                });

            modelBuilder.Entity("API.Models.EntityFramework.NotificationMessage", b =>
                {
                    b.HasOne("API.Models.EntityFramework.Message", "Message")
                        .WithMany("NotificationsMessage")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.Notification", "LaNotification")
                        .WithOne("NotificationMessages")
                        .HasForeignKey("API.Models.EntityFramework.NotificationMessage", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LaNotification");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("API.Models.EntityFramework.NotificationModificationAnnonce", b =>
                {
                    b.HasOne("API.Models.EntityFramework.Annonce", "Annonce")
                        .WithMany("NotificationsModificationAnnonces")
                        .HasForeignKey("AnnonceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.Notification", "LaNotification")
                        .WithOne("NotificationModifications")
                        .HasForeignKey("API.Models.EntityFramework.NotificationModificationAnnonce", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Annonce");

                    b.Navigation("LaNotification");
                });

            modelBuilder.Entity("API.Models.EntityFramework.NotificationNouvelleAnnonce", b =>
                {
                    b.HasOne("API.Models.EntityFramework.Annonce", "Annonce")
                        .WithMany("NotificationsNouvelleAnnonces")
                        .HasForeignKey("AnnonceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.Notification", "LaNotification")
                        .WithOne("NotificationNouvellesAnnonces")
                        .HasForeignKey("API.Models.EntityFramework.NotificationNouvelleAnnonce", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Annonce");

                    b.Navigation("LaNotification");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Recense", b =>
                {
                    b.HasOne("API.Models.EntityFramework.Annonce", "Annonce")
                        .WithMany("Tags")
                        .HasForeignKey("AnnonceId")
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.Tag", "Tag")
                        .WithMany("Annonces")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Annonce");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Signalement", b =>
                {
                    b.HasOne("API.Models.EntityFramework.TypeSignalement", "TypeSignalement")
                        .WithMany("Signalements")
                        .HasForeignKey("SignalementTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.Utilisateur", "Utilisateur")
                        .WithMany("Signalements")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TypeSignalement");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("API.Models.EntityFramework.SignalementAnnonce", b =>
                {
                    b.HasOne("API.Models.EntityFramework.Annonce", "Annonce")
                        .WithMany("Signalements")
                        .HasForeignKey("AnnonceSignaleeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.Signalement", "Signalement")
                        .WithOne("SignalementsAnnonce")
                        .HasForeignKey("API.Models.EntityFramework.SignalementAnnonce", "SignalementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Annonce");

                    b.Navigation("Signalement");
                });

            modelBuilder.Entity("API.Models.EntityFramework.SignalementAvis", b =>
                {
                    b.HasOne("API.Models.EntityFramework.NoteUtilisateur", "Avis")
                        .WithMany("Signalements")
                        .HasForeignKey("AvisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.Signalement", "Signalement")
                        .WithOne("SignalementsAvis")
                        .HasForeignKey("API.Models.EntityFramework.SignalementAvis", "SignalementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avis");

                    b.Navigation("Signalement");
                });

            modelBuilder.Entity("API.Models.EntityFramework.SignalementUtilisateur", b =>
                {
                    b.HasOne("API.Models.EntityFramework.Signalement", "Signalement")
                        .WithOne("SignalementsUtilisateur")
                        .HasForeignKey("API.Models.EntityFramework.SignalementUtilisateur", "SignalementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.Utilisateur", "UtilisateurSignale")
                        .WithMany("SignalementsUtilisateurs")
                        .HasForeignKey("UtilisateurSignaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Signalement");

                    b.Navigation("UtilisateurSignale");
                });

            modelBuilder.Entity("API.Models.EntityFramework.SousCategorie", b =>
                {
                    b.HasOne("API.Models.EntityFramework.Categorie", "Categorie")
                        .WithMany("SousCategories")
                        .HasForeignKey("CategorieId")
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Taille", b =>
                {
                    b.HasOne("API.Models.EntityFramework.Categorie", "Categorie")
                        .WithMany("Tailles")
                        .HasForeignKey("CategorieTailleId")
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Transaction", b =>
                {
                    b.HasOne("API.Models.EntityFramework.Conversation", "Conversation")
                        .WithOne("Transaction")
                        .HasForeignKey("API.Models.EntityFramework.Transaction", "ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Utilisateur", b =>
                {
                    b.HasOne("API.Models.EntityFramework.Adresse", "Adresse")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("AdresseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Adresse_Utilisateur");

                    b.HasOne("API.Models.EntityFramework.Photo", "PhotoProfil")
                        .WithOne("Utilisateur")
                        .HasForeignKey("API.Models.EntityFramework.Utilisateur", "PhotoId");

                    b.HasOne("API.Models.EntityFramework.RoleUtilisateur", "Role")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.StatutUtilisateur", "Statut")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("StatutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Adresse");

                    b.Navigation("PhotoProfil");

                    b.Navigation("Role");

                    b.Navigation("Statut");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Vend", b =>
                {
                    b.HasOne("API.Models.EntityFramework.Conversation", "LaConversation")
                        .WithOne("Vendeur")
                        .HasForeignKey("API.Models.EntityFramework.Vend", "ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.EntityFramework.Utilisateur", "UtilisateurVendeur")
                        .WithMany("Ventes")
                        .HasForeignKey("UtilisateurVendeurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LaConversation");

                    b.Navigation("UtilisateurVendeur");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Adresse", b =>
                {
                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Annonce", b =>
                {
                    b.Navigation("Couleurs");

                    b.Navigation("Decisions");

                    b.Navigation("LesConversations");

                    b.Navigation("NotificationsModificationAnnonces");

                    b.Navigation("NotificationsNouvelleAnnonces");

                    b.Navigation("Photos");

                    b.Navigation("Signalements");

                    b.Navigation("Tags");

                    b.Navigation("UtilisateursFavoris");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Categorie", b =>
                {
                    b.Navigation("Annonces");

                    b.Navigation("SousCategories");

                    b.Navigation("Tailles");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Conversation", b =>
                {
                    b.Navigation("Acheteur");

                    b.Navigation("Messages");

                    b.Navigation("Transaction");

                    b.Navigation("Vendeur");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Couleur", b =>
                {
                    b.Navigation("Annonces");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Decision_suspension", b =>
                {
                    b.Navigation("DemandesRes");
                });

            modelBuilder.Entity("API.Models.EntityFramework.EtatArticle", b =>
                {
                    b.Navigation("Annonces");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Marque", b =>
                {
                    b.Navigation("Annonces");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Message", b =>
                {
                    b.Navigation("MessageDemande");

                    b.Navigation("MessageTexte");

                    b.Navigation("MessageValidation");

                    b.Navigation("NotificationsMessage");
                });

            modelBuilder.Entity("API.Models.EntityFramework.MessageDemande", b =>
                {
                    b.Navigation("ContreOffres");
                });

            modelBuilder.Entity("API.Models.EntityFramework.MessageTexte", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("API.Models.EntityFramework.NoteUtilisateur", b =>
                {
                    b.Navigation("Signalements");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Notification", b =>
                {
                    b.Navigation("NotificationAdmins");

                    b.Navigation("NotificationAvertissements");

                    b.Navigation("NotificationMessages");

                    b.Navigation("NotificationModifications");

                    b.Navigation("NotificationNouvellesAnnonces");
                });

            modelBuilder.Entity("API.Models.EntityFramework.NotificationType", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Photo", b =>
                {
                    b.Navigation("Annonces");

                    b.Navigation("Messages");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("API.Models.EntityFramework.RoleUtilisateur", b =>
                {
                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Signalement", b =>
                {
                    b.Navigation("SignalementsAnnonce");

                    b.Navigation("SignalementsAvis");

                    b.Navigation("SignalementsUtilisateur");
                });

            modelBuilder.Entity("API.Models.EntityFramework.SousCategorie", b =>
                {
                    b.Navigation("Annonces");
                });

            modelBuilder.Entity("API.Models.EntityFramework.StatutAnnonce", b =>
                {
                    b.Navigation("Annonces");
                });

            modelBuilder.Entity("API.Models.EntityFramework.StatutConversation", b =>
                {
                    b.Navigation("Conversations");
                });

            modelBuilder.Entity("API.Models.EntityFramework.StatutUtilisateur", b =>
                {
                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Tag", b =>
                {
                    b.Navigation("Annonces");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Taille", b =>
                {
                    b.Navigation("Annonces");
                });

            modelBuilder.Entity("API.Models.EntityFramework.TypeSignalement", b =>
                {
                    b.Navigation("Signalements");
                });

            modelBuilder.Entity("API.Models.EntityFramework.TypeSuspension", b =>
                {
                    b.Navigation("Decision_suspensions");
                });

            modelBuilder.Entity("API.Models.EntityFramework.Utilisateur", b =>
                {
                    b.Navigation("Abonnements");

                    b.Navigation("Abonnes");

                    b.Navigation("Achats");

                    b.Navigation("Annonces");

                    b.Navigation("AnnoncesFavorites");

                    b.Navigation("BloqueParUtilisateurs");

                    b.Navigation("DemandesRestauration");

                    b.Navigation("LesDecisions");

                    b.Navigation("LesSuspensions");

                    b.Navigation("Messages");

                    b.Navigation("NotesAuteur");

                    b.Navigation("NotesCible");

                    b.Navigation("Notifications");

                    b.Navigation("Signalements");

                    b.Navigation("SignalementsUtilisateurs");

                    b.Navigation("UtilisateursBloques");

                    b.Navigation("Ventes");
                });
#pragma warning restore 612, 618
        }
    }
}
